spring:
  application:
    name: paymentService
  config:
    import: optional:configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9000}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-hj6kwec2hubzqrrk.eu.auth0.com/

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8082
